### ISSUE TITLE
How could I evaluate single image

### ISSUE THREAD

**Issue by Yangxx12138** [rezazad68/BCDUnet_DIBCO#2]

**Comment by rezazad68** [comment]
Put all your samples (either one or several) on one folder and change the data set add inside the code. It should work fine.

**Comment by SB2020-eye** [comment]
Thank you for making this available, and for your answer here.

I apologize -- I am very much a beginner.

1. Where do we "change the data set" and "add inside the code"?

2. And what do we do to run and get the output once we have done that?

I would so appreciate knowing! Thanks.
